version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: lummen_postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01Ummilhao
      POSTGRES_DB: banco_lummen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lummen_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: lummen_backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:01Ummilhao@postgres:5432/banco_lummen?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3002
      NODE_ENV: production
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/src/uploads   # ðŸ”¥ AQUI â€” persistÃªncia real das fotos

volumes:
  postgres_data:
